### ISSUE TITLE
[STORY] Setup the repo

### ISSUE THREAD

**Issue by Suraii** [EIP-Pivot/pivot#1]
# Utilisateur

# Besoin

Building and resolving dependencies easily

# Description

A configured build tool chain that automates both building and dependencies resolving.

# Definition Of Done

- [x] Labels are created to organize the issues by categories (3D, documentation, UI, etc...)
- [x] The most appropriated build tool chain (CMake, build2,...) is chosen and used
- [x] The build tool chain allows users to easily build the code in a 'build' folder
- [x] The build tool chain allows users to easily resolve dependencies
- [x] The build tool chain allows users to compile code in Release mode or Debug mode

# Charge de travail

2

**Comment by zcorniere** [comment]
Are we using .cpp file or .cxx ?
