### ISSUE TITLE
[STORY] Design and Implement the Systems Manager

### ISSUE THREAD

**Issue by Suraii** [EIP-Pivot/pivot#14]
# Users

# Need

Execute functions on given components

# Description

A class that handle "systems" (functions to execute with the specified components as an input), in an ECS way.

# Definition Of Done

- [ ] We can add new systems, by specifying both the code to execute and the components to take as inputs
- [ ] The class execute all the systems on tick while giving them the input they need
- [ ] We can add systems that can access other parts of the game than the components, like the modules
- [ ] The class can automatically register unregistered components given as inputs

# Workload

8

**Comment by zcorniere** [comment]
I think we should take the multithread part in another issue, because it is quite a big subject, especially regarding interaction with other part of the engine.
